name: Build & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: hhtdev/hhtdev_portfolio:latest
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Remote SSH pull, stop and run
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            docker pull hhtdev/hhtdev_portfolio:latest
            docker stop hhtdev_portfolio || true
            docker rm hhtdev_portfolio || true
            docker run -d --name hhtdev_portfolio -p 3000:3000 hhtdev/hhtdev_portfolio:latest

